language: go

sudo: required

services:
  - docker

go:
  - 1.9.x
  - 1.10.x
  - tip

addons:
  apt:
    sources:
      - sourceline: 'ppa:zfs-native/stable'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install linux-headers-`uname -r`
  - sudo apt-get install ubuntu-zfs
  - sudo modprobe zfs
  - source ./travis-setup.sh

env:
  - AZURE_CUSTOM_ENDPOINT=127.0.0.1:10000 AWS_S3_CUSTOM_ENDPOINT=http://127.0.0.1:9000 AWS_REGION=us-east-1

install:
  - $GOPATH/bin/gometalinter --install
  - make get

script:
  - sudo -E env "PATH=$PATH" go test -v -covermode=count -coverprofile=coverage.out ./...
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
  - make fmt vet build

after_script: source ./travis-teardown.sh
