language: go

go:
  - 1.8.x
  - 1.9.x
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/alecthomas/gometalinter
  - go get github.com/mitchellh/gox

install:
  - $HOME/gopath/bin/gometalinter --install
  - make get

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
  - make fmt vet test test-race build
